language: go
sudo: false
go:
  - 1.4

env:
  - PATH="${PATH}:${HOME}/.local/bin"

addons:
  apt:
    packages:
    - libpcap-dev

install:
  - go clean -i net
  - go install -tags netgo std
  - pip install --user --upgrade gcloud gsutil
  - openssl aes-256-cbc
    -K $encrypted_5ba036e89377_key -iv $encrypted_5ba036e89377_iv
    -in bin/setup-ci-secrets.enc -out bin/setup-ci-secrets -d
  - chmod +x bin/setup-ci-secrets
  - make travis

script:
  - bin/lint .
  - make tests

after_success:
  - go get github.com/mattn/goveralls
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - bin/setup-ci-secrets
  - site/build-and-publish.sh
